### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheDsm112** [TrevorLuckey/KH2Tracker#38]
Which memory addresses are read when using the auto tracker? A list would be appreciated if you have one.

**Comment by TrevorLuckey** [comment]
I don't have a list of everything written down anywhere but most every address that is used is listed in the autotracker.cs file.
Val's repo for the randomizer is useful for finding addresses of things in the game as well https://github.com/afresquet/kh2fm-randomizer

**Comment by TheDsm112** [comment]
The listed addresses in the cs files seem to differ from the addresses when viewed in the game's active memory. In the AutoTracker.cs, it shows the Promise Charm being tracked using address 0032F1F0. When viewing that address with Cheat Engine, it shows an unknown or invalid value. When looking for myself, it shows a Promise Charm under address 2032F1C4.
