### ISSUE TITLE
Broadcast window appears to OBS as a different resolution if on a different monitor to primary monitor

### ISSUE THREAD

**Issue by RansomTime** [TrevorLuckey/KH2Tracker#49]
Not sure if this is an OBS issue or an issue with the tracker, but if the broadcast window is on a different resolution to my primary monitor, it seems to be captured incorrectly by OBS

![image](https://user-images.githubusercontent.com/47819665/114744350-82eff400-9d45-11eb-955e-010be0cfdf7b.png)
![image](https://user-images.githubusercontent.com/47819665/114744393-8f744c80-9d45-11eb-850a-770ec38f54a3.png)

First image is what OBS sees when it's on another monitor, 2nd image is when it's on my primary monitor.

My primary monitor is 2560 x 1440 and my other monitors are 1920 x 1080 which might be what's causing this issue.

As a workaround, moving the broadcast window to my primary monitor works, but the broadcast window doesn't initially appear on that monitor, so I was confused trying to figure out what was up.

**Comment by TrevorLuckey** [comment]
I believe this is an issue with Windows DPI scaling. I don't think there's anything on the tracker side that can be done to fix it. You would probably have to find something in either Windows or OBS, or stick to the workaround you found to make it work properly
